apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deployment: slack-socket-mode
resources:
- deployment.yaml
images:
- name: ghcr.io/Mariamakbbh/slack-socket-mode
  newTag: v0.0.1
